CREATE TABLE IF NOT EXISTS MEMBER (
    member_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COFFEE (
    coffee_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kor_name VARCHAR(100) NOT NULL,
    eng_name VARCHAR(100) NOT NULL,
    price INT NOT NULL,
    coffee_code CHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS(
    order_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);

CREATE TABLE IF NOT EXISTS ORDER_COFFEE(
    order_coffee_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    coffee_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),
    FOREIGN KEY (coffee_id) REFERENCES COFFEE(coffee_id)
);